In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [2]:
!nvidia-smi

Mon May 15 06:35:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:26:00.0  On |                  N/A |
| 31%   40C    P5    N/A /  75W |    303MiB /  4032MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to tesors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# dimention of the scalar 
scalar.ndim


0

In [5]:
# get tensor back as python int
scalar.item()

7

In [6]:
# create Vectro using tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [11]:
# matrix
matrix1 = torch.tensor([[7,8],[9,10]])
print(matrix1)
print(matrix1.shape)

tensor([[ 7,  8],
        [ 9, 10]])
torch.Size([2, 2])


In [12]:
matrix1[1]

tensor([ 9, 10])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])